// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/task-force-themes/Neon.tsx": () => import("../components/mockups/task-force-themes/Neon.tsx"),
  "./components/mockups/task-force-themes/Sunshine.tsx": () => import("../components/mockups/task-force-themes/Sunshine.tsx"),
  "./components/mockups/task-force-themes/Vibrant.tsx": () => import("../components/mockups/task-force-themes/Vibrant.tsx")
};
